$(document).ready(function(){
        $('#aniadir').click(function(){
            dcp=$('#cetaem').val();
            atc=$('#atc').val();
            long=$('#nombre').val();
            codigo_atc=$('codigoatc').val();
            array=[];
            $("#vias option").each(function(){
              array.push($(this).attr('value'));
             });
        $.ajax({
                type:"POST",
                url:"insertar_medicamento.php",
                data:{
                    dcp:dcp,
                    atc:atc,
                    long:long,
                    codigo_atc_codigo_atc,
                    array:array
                },
            success:function(data){
               alert(data);
            }
        })
});
});